In [1]:
import numpy as np

def strassen(A, B):
    n = A.shape[0]
    if n == 1:
        return A * B
    else:
        # Разбиение матрицы A на 4 части
        A11 = A[:n//2, :n//2]
        A12 = A[:n//2, n//2:]
        A21 = A[n//2:, :n//2]
        A22 = A[n//2:, n//2:]
        
        # Разбиение матрицы B на 4 части
        B11 = B[:n//2, :n//2]
        B12 = B[:n//2, n//2:]
        B21 = B[n//2:, :n//2]
        B22 = B[n//2:, n//2:]
        
        # Рекурсивно вычисляем 7 подматриц
        M1 = strassen(A11 + A22, B11 + B22)
        M2 = strassen(A21 + A22, B11)
        M3 = strassen(A11, B12 - B22)
        M4 = strassen(A22, B21 - B11)
        M5 = strassen(A11 + A12, B22)
        M6 = strassen(A21 - A11, B11 + B12)
        M7 = strassen(A12 - A22, B21 + B22)
        
        # Собираем результирующую матрицу из 7 подматриц
        C11 = M1 + M4 - M5 + M7
        C12 = M3 + M5
        C21 = M2 + M4
        C22 = M1 - M2 + M3 + M6
        C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))
        return C



In [57]:
# Создаем матрицы размера 4 x 4
A = np.array([[2, 0, 1, 2], [0, 2, 1, 0], [1, 2, 0, 2], [2, 0, 1, 0]])
B = np.array([[0, 1, 1, 0], [2, 1, 0, 2], [2, 0, 2, 2], [0, 2, 0, 1]])



In [58]:
n = A.shape[0]

In [59]:
# Разбиение матрицы A на 4 части
A11 = A[:n//2, :n//2]
A12 = A[:n//2, n//2:]
A21 = A[n//2:, :n//2]
A22 = A[n//2:, n//2:]

In [60]:
A11

array([[2, 0],
       [0, 2]])

In [61]:
A12

array([[1, 2],
       [1, 0]])

In [62]:
A21

array([[1, 2],
       [2, 0]])

In [63]:
A22

array([[0, 2],
       [1, 0]])

In [64]:
# Разбиение матрицы B на 4 части
B11 = B[:n//2, :n//2]
B12 = B[:n//2, n//2:]
B21 = B[n//2:, :n//2]
B22 = B[n//2:, n//2:]

In [65]:
B11

array([[0, 1],
       [2, 1]])

In [66]:
B12

array([[1, 0],
       [0, 2]])

In [67]:
B21

array([[2, 0],
       [0, 2]])

In [68]:
B22

array([[2, 2],
       [0, 1]])

In [83]:
A11 + A22

array([[2, 2],
       [1, 2]])

In [84]:
B11 + B22

array([[2, 3],
       [2, 2]])

In [85]:
A21 + A22

array([[1, 4],
       [3, 0]])

In [87]:
B12 - B22

array([[-1, -2],
       [ 0,  1]])

In [88]:
B21 - B11

array([[ 2, -1],
       [-2,  1]])

In [89]:
A11 + A12

array([[3, 2],
       [1, 2]])

In [90]:
A21 - A11

array([[-1,  2],
       [ 2, -2]])

In [91]:
B11 + B12


array([[1, 1],
       [2, 3]])

In [92]:
A12 - A22

array([[1, 0],
       [0, 0]])

In [93]:
B21 + B22

array([[4, 2],
       [0, 3]])

In [69]:
# Рекурсивно вычисляем 7 подматриц
M1 = strassen(A11 + A22, B11 + B22)
M2 = strassen(A21 + A22, B11)
M3 = strassen(A11, B12 - B22)
M4 = strassen(A22, B21 - B11)
M5 = strassen(A11 + A12, B22)
M6 = strassen(A21 - A11, B11 + B12)
M7 = strassen(A12 - A22, B21 + B22)

In [70]:
M1

array([[ 8, 10],
       [ 6,  7]])

In [71]:
M2

array([[8, 5],
       [0, 3]])

In [72]:
M3

array([[-2, -4],
       [ 0,  2]])

In [73]:
M4

array([[-4,  2],
       [ 2, -1]])

In [74]:
M5

array([[6, 8],
       [2, 4]])

In [75]:
M6

array([[ 3,  5],
       [-2, -4]])

In [76]:
M7

array([[4, 2],
       [0, 0]])

In [77]:
# Собираем результирующую матрицу из 7 подматриц
C11 = M1 + M4 - M5 + M7
C12 = M3 + M5
C21 = M2 + M4
C22 = M1 - M2 + M3 + M6

In [82]:
# Умножаем матрицы методом Штрассена
C = strassen(A, B)

# Выводим результат
print(C)

[[2 6 4 4]
 [6 2 2 6]
 [4 7 1 6]
 [2 2 4 2]]
