In [221]:
import numpy as np

def strassen(A, B):
    n = A.shape[0]
    if n == 1:
        return A * B
    else:
        # Разбиение матрицы A на 4 части
        A11 = A[:n//2, :n//2]
        A12 = A[:n//2, n//2:]
        A21 = A[n//2:, :n//2]
        A22 = A[n//2:, n//2:]
        
        # Разбиение матрицы B на 4 части
        B11 = B[:n//2, :n//2]
        B12 = B[:n//2, n//2:]
        B21 = B[n//2:, :n//2]
        B22 = B[n//2:, n//2:]
        
        # Рекурсивно вычисляем 7 подматриц
        M1 = strassen(A11 + A22, B11 + B22)
        M2 = strassen(A21 + A22, B11)
        M3 = strassen(A11, B12 - B22)
        M4 = strassen(A22, B21 - B11)
        M5 = strassen(A11 + A12, B22)
        M6 = strassen(A21 - A11, B11 + B12)
        M7 = strassen(A12 - A22, B21 + B22)
        
        # Собираем результирующую матрицу из 7 подматриц
        C11 = M1 + M4 - M5 + M7
        C12 = M3 + M5
        C21 = M2 + M4
        C22 = M1 - M2 + M3 + M6
        C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))
        return C



In [222]:
# Создаем матрицы размера 4 x 4
#A = np.array([[2, 0, 1, 2], [0, 2, 1, 0], [1, 2, 0, 2], [2, 0, 1, 0]])
#B = np.array([[0, 1, 1, 0], [2, 1, 0, 2], [2, 0, 2, 2], [0, 2, 0, 1]])

A = np.array([[-2, 1, 0, 3], [1, 0, 4, -1], [2, 1 ,0 ,3], [3, -2, 1, 0]])
B = np.array([[0, 2, 3 , -1], [2, 1, 0 , 4], [3, 0, -2, 1], [1, -2, 1, 0]])


In [223]:
n = A.shape[0]

In [224]:
# Разбиение матрицы A на 4 части
A11 = A[:n//2, :n//2]
A12 = A[:n//2, n//2:]
A21 = A[n//2:, :n//2]
A22 = A[n//2:, n//2:]

In [225]:
A11

array([[-2,  1],
       [ 1,  0]])

In [226]:
A12

array([[ 0,  3],
       [ 4, -1]])

In [227]:
A21

array([[ 2,  1],
       [ 3, -2]])

In [228]:
A22

array([[0, 3],
       [1, 0]])

In [229]:
# Разбиение матрицы B на 4 части
B11 = B[:n//2, :n//2]
B12 = B[:n//2, n//2:]
B21 = B[n//2:, :n//2]
B22 = B[n//2:, n//2:]

In [230]:
B11

array([[0, 2],
       [2, 1]])

In [231]:
B12

array([[ 3, -1],
       [ 0,  4]])

In [232]:
B21

array([[ 3,  0],
       [ 1, -2]])

In [233]:
B22

array([[-2,  1],
       [ 1,  0]])

#### Надо выписывать итоговые матрицы которые начинают перечисляться здесь

# для D0:

In [234]:
test1 = A11 + A22
test1

array([[-2,  4],
       [ 2,  0]])

In [235]:
test2 = B11 + B22
test2

array([[-2,  3],
       [ 3,  1]])

In [236]:
print(f'{test1[0,0]}*{test2[0,0]}+{test1[0,1]}*{test2[1,0]} _ {test1[0,0]}*{test2[0,1]}+{test1[0,1]}*{test2[1,1]} \n {test1[1,0]}*{test2[0,0]}+{test1[1,1]}*{test2[1,0]} _ {test1[1,0]}*{test2[0,1]}+{test1[1,1]}*{test2[1,1]}')

-2*-2+4*3 _ -2*3+4*1 
 2*-2+0*3 _ 2*3+0*1


In [237]:
D0 = strassen(A11 + A22, B11 + B22)
D0

array([[16, -2],
       [-4,  6]])

# d1


In [238]:
test1 = A12 - A22
test1

array([[ 0,  0],
       [ 3, -1]])

In [239]:
test2 = B21 + B22
test2

array([[ 1,  1],
       [ 2, -2]])

In [240]:
D1 = strassen(A12 - A22, B21 + B22)
D1

array([[0, 0],
       [1, 5]])

In [241]:
print(f'{test1[0,0]}*{test2[0,0]}+{test1[0,1]}*{test2[1,0]} _ {test1[0,0]}*{test2[0,1]}+{test1[0,1]}*{test2[1,1]} \n {test1[1,0]}*{test2[0,0]}+{test1[1,1]}*{test2[1,0]} _ {test1[1,0]}*{test2[0,1]}+{test1[1,1]}*{test2[1,1]}')

0*1+0*2 _ 0*1+0*-2 
 3*1+-1*2 _ 3*1+-1*-2


# d2

In [242]:
test1 = A21 - A11
test1

array([[ 4,  0],
       [ 2, -2]])

In [243]:
test2 = B11 + B12
test2

array([[3, 1],
       [2, 5]])

In [244]:
D2 = strassen(A21 - A11, B11 + B12)
D2

array([[12,  4],
       [ 2, -8]])

In [245]:
print(f'{test1[0,0]}*{test2[0,0]}+{test1[0,1]}*{test2[1,0]} _ {test1[0,0]}*{test2[0,1]}+{test1[0,1]}*{test2[1,1]} \n {test1[1,0]}*{test2[0,0]}+{test1[1,1]}*{test2[1,0]} _ {test1[1,0]}*{test2[0,1]}+{test1[1,1]}*{test2[1,1]}')

4*3+0*2 _ 4*1+0*5 
 2*3+-2*2 _ 2*1+-2*5


# d3

In [246]:
test1 = A11 + A12
test1

array([[-2,  4],
       [ 5, -1]])

In [247]:
test2 = B22
test2

array([[-2,  1],
       [ 1,  0]])

In [248]:
D3 = strassen(A11 + A12, B22)
D3

array([[  8,  -2],
       [-11,   5]])

In [249]:
print(f'{test1[0,0]}*{test2[0,0]}+{test1[0,1]}*{test2[1,0]} _ {test1[0,0]}*{test2[0,1]}+{test1[0,1]}*{test2[1,1]} \n {test1[1,0]}*{test2[0,0]}+{test1[1,1]}*{test2[1,0]} _ {test1[1,0]}*{test2[0,1]}+{test1[1,1]}*{test2[1,1]}')

-2*-2+4*1 _ -2*1+4*0 
 5*-2+-1*1 _ 5*1+-1*0


# d4

In [250]:
test1 = A11
test1

array([[-2,  1],
       [ 1,  0]])

In [251]:
test2 = B12 - B22
test2

array([[ 5, -2],
       [-1,  4]])

In [252]:
D4 = strassen(A11, B12 - B22)
D4

array([[-11,   8],
       [  5,  -2]])

In [253]:
print(f'{test1[0,0]}*{test2[0,0]}+{test1[0,1]}*{test2[1,0]} _ {test1[0,0]}*{test2[0,1]}+{test1[0,1]}*{test2[1,1]} \n {test1[1,0]}*{test2[0,0]}+{test1[1,1]}*{test2[1,0]} _ {test1[1,0]}*{test2[0,1]}+{test1[1,1]}*{test2[1,1]}')

-2*5+1*-1 _ -2*-2+1*4 
 1*5+0*-1 _ 1*-2+0*4


# d5 

In [254]:
test1 = A22
test1

array([[0, 3],
       [1, 0]])

In [255]:
test2 = B21 - B11
test2

array([[ 3, -2],
       [-1, -3]])

In [256]:
D5 = strassen(A22, B21 - B11)
D5

array([[-3, -9],
       [ 3, -2]])

In [257]:
print(f'{test1[0,0]}*{test2[0,0]}+{test1[0,1]}*{test2[1,0]} _ {test1[0,0]}*{test2[0,1]}+{test1[0,1]}*{test2[1,1]} \n {test1[1,0]}*{test2[0,0]}+{test1[1,1]}*{test2[1,0]} _ {test1[1,0]}*{test2[0,1]}+{test1[1,1]}*{test2[1,1]}')

0*3+3*-1 _ 0*-2+3*-3 
 1*3+0*-1 _ 1*-2+0*-3


# d6

In [258]:
test1 = A21 + A22
test1

array([[ 2,  4],
       [ 4, -2]])

In [259]:
test2 = B11
test2

array([[0, 2],
       [2, 1]])

In [260]:
D6 = strassen(A21 + A22, B11)
D6

array([[ 8,  8],
       [-4,  6]])

In [261]:
print(f'{test1[0,0]}*{test2[0,0]}+{test1[0,1]}*{test2[1,0]} _ {test1[0,0]}*{test2[0,1]}+{test1[0,1]}*{test2[1,1]} \n {test1[1,0]}*{test2[0,0]}+{test1[1,1]}*{test2[1,0]} _ {test1[1,0]}*{test2[0,1]}+{test1[1,1]}*{test2[1,1]}')

2*0+4*2 _ 2*2+4*1 
 4*0+-2*2 _ 4*2+-2*1


In [262]:
# Собираем результирующую матрицу из 7 подматриц
C11 = D0 + D1 - D3 + D5
C21 = D5 + D6
C12 = D3 + D4
C22 = D0 + D2 + D4 - D6
Citog = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))
Citog

array([[  5,  -9,  -3,   6],
       [ 11,   4,  -6,   3],
       [  5,  -1,   9,   2],
       [ -1,   4,   7, -10]])